import { ComponentTemplate } from './types';

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  {
    id: 'resistor',
    name: 'Resistor',
    category: 'Passive',
    symbol: 'resistor',
    pins: [
      { id: '1', name: 'Pin 1', position: { x: -20, y: 0 } },
      { id: '2', name: 'Pin 2', position: { x: 20, y: 0 } },
    ],
    defaultValues: { resistance: '10k' },
  },
  {
    id: 'capacitor',
    name: 'Capacitor',
    category: 'Passive',
    symbol: 'capacitor',
    pins: [
      { id: '1', name: 'Pin 1', position: { x: -10, y: 0 } },
      { id: '2', name: 'Pin 2', position: { x: 10, y: 0 } },
    ],
    defaultValues: { capacitance: '100nF' },
  },
  {
    id: 'led',
    name: 'LED',
    category: 'Active',
    symbol: 'led',
    pins: [
      { id: 'a', name: 'Anode', position: { x: -15, y: 0 } },
      { id: 'k', name: 'Cathode', position: { x: 15, y: 0 } },
    ],
    defaultValues: { color: 'Red', Vf: '2.0V' },
  },
  {
    id: 'battery',
    name: 'Battery',
    category: 'Power',
    symbol: 'battery',
    pins: [
      { id: 'pos', name: 'Positive', position: { x: 0, y: -15 } },
      { id: 'neg', name: 'Negative', position: { x: 0, y: 15 } },
    ],
    defaultValues: { voltage: '9V' },
  },
  {
    id: 'ic-8',
    name: '8-Pin IC',
    category: 'Integrated',
    symbol: 'ic-8',
    pins: [
      { id: '1', name: '1', position: { x: -30, y: -30 } },
      { id: '2', name: '2', position: { x: -30, y: -10 } },
      { id: '3', name: '3', position: { x: -30, y: 10 } },
      { id: '4', name: '4', position: { x: -30, y: 30 } },
      { id: '5', name: '5', position: { x: 30, y: 30 } },
      { id: '6', name: '6', position: { x: 30, y: 10 } },
      { id: '7', name: '7', position: { x: 30, y: -10 } },
      { id: '8', name: '8', position: { x: 30, y: -30 } },
    ],
    defaultValues: { part: 'NE555' },
  },
  {
    id: 'mosfet',
    name: 'MOSFET',
    category: 'Active',
    symbol: 'mosfet',
    pins: [
      { id: 'g', name: 'Gate', position: { x: -15, y: 0 } },
      { id: 'd', name: 'Drain', position: { x: 15, y: -15 } },
      { id: 's', name: 'Source', position: { x: 15, y: 15 } },
    ],
    defaultValues: { type: 'N-Channel', Vgs: '20V' },
  },
  {
    id: 'switch',
    name: 'Switch',
    category: 'Passive',
    symbol: 'switch',
    pins: [
      { id: '1', name: '1', position: { x: -15, y: 0 } },
      { id: '2', name: '2', position: { x: 15, y: 0 } },
    ],
    defaultValues: { state: 'Open' },
  },
  {
    id: 'opamp',
    name: 'Op-Amp (TL072)',
    category: 'Integrated',
    symbol: 'opamp',
    pins: [
      { id: 'in+', name: 'IN+', position: { x: -20, y: -10 } },
      { id: 'in-', name: 'IN-', position: { x: -20, y: 10 } },
      { id: 'v+', name: 'V+', position: { x: 0, y: -20 } },
      { id: 'v-', name: 'V-', position: { x: 0, y: 20 } },
      { id: 'out', name: 'OUT', position: { x: 20, y: 0 } },
    ],
    defaultValues: { part: 'TL072' },
  },
  {
    id: 'reg-7805',
    name: 'Voltage Reg (+5V)',
    category: 'Power',
    symbol: 'regulator',
    pins: [
      { id: 'in', name: 'VIN', position: { x: -20, y: 0 } },
      { id: 'gnd', name: 'GND', position: { x: 0, y: 15 } },
      { id: 'out', name: 'VOUT', position: { x: 20, y: 0 } },
    ],
    defaultValues: { part: 'L7805' },
  },
  {
    id: 'esp32-wroom',
    name: 'ESP32-WROOM',
    category: 'Module',
    symbol: 'microcontroller',
    pins: [
      { id: '3v3', name: '3V3', position: { x: -30, y: -40 } },
      { id: 'en', name: 'EN', position: { x: -30, y: -30 } },
      { id: 'vp', name: 'VP', position: { x: -30, y: -20 } },
      { id: 'vn', name: 'VN', position: { x: -30, y: -10 } },
      { id: 'gnd', name: 'GND', position: { x: 30, y: 40 } },
      { id: 'tx', name: 'TXD0', position: { x: 30, y: -40 } },
      { id: 'rx', name: 'RXD0', position: { x: 30, y: -30 } },
      { id: 'io0', name: 'IO0', position: { x: 30, y: -20 } },
      { id: 'io2', name: 'IO2', position: { x: 30, y: -10 } },
    ],
    defaultValues: { flash: '4MB', psram: 'None' },
  },
  {
    id: 'led-red',
    name: 'LED (Red)',
    category: 'Active',
    symbol: 'led',
    pins: [
      { id: 'a', name: 'A', position: { x: -10, y: 0 } },
      { id: 'k', name: 'K', position: { x: 10, y: 0 } },
    ],
    defaultValues: { Vf: '1.8V', If: '20mA' },
  },
  {
    id: 'and-gate',
    name: 'AND Gate (7408)',
    category: 'Integrated',
    symbol: 'logic-and',
    pins: [
      { id: '1', name: 'A1', position: { x: -20, y: -10 } },
      { id: '2', name: 'B1', position: { x: -20, y: 10 } },
      { id: '3', name: 'Y1', position: { x: 20, y: 0 } },
    ],
    defaultValues: { part: '74HC08' },
  },
  {
    id: 'or-gate',
    name: 'OR Gate (7432)',
    category: 'Integrated',
    symbol: 'logic-or',
    pins: [
      { id: '1', name: 'A1', position: { x: -20, y: -10 } },
      { id: '2', name: 'B1', position: { x: -20, y: 10 } },
      { id: '3', name: 'Y1', position: { x: 20, y: 0 } },
    ],
    defaultValues: { part: '74HC32' },
  },
  {
    id: 'temp-sensor',
    name: 'TMP36 Temp',
    category: 'Other',
    symbol: 'sensor',
    pins: [
      { id: 'vcc', name: 'VCC', position: { x: -10, y: -15 } },
      { id: 'out', name: 'OUT', position: { x: 15, y: 0 } },
      { id: 'gnd', name: 'GND', position: { x: -10, y: 15 } },
    ],
    defaultValues: { range: '-40 to +125C' },
  },
  {
    id: 'ldr',
    name: 'LDR Photocell',
    category: 'Other',
    symbol: 'ldr',
    pins: [
      { id: '1', name: '1', position: { x: -15, y: 0 } },
      { id: '2', name: '2', position: { x: 15, y: 0 } },
    ],
    defaultValues: { type: 'GL55' },
  },
  {
    id: 'atmega328p',
    name: 'ATmega328P',
    category: 'Integrated',
    symbol: 'microcontroller',
    pins: [
      { id: '1', name: 'PC6/RESET', position: { x: -40, y: -45 } },
      { id: '2', name: 'PD0/RXD', position: { x: -40, y: -35 } },
      { id: '3', name: 'PD1/TXD', position: { x: -40, y: -25 } },
      { id: '4', name: 'PD2/INT0', position: { x: -40, y: -15 } },
      { id: '7', name: 'VCC', position: { x: -40, y: 5 } },
      { id: '8', name: 'GND', position: { x: -40, y: 15 } },
      { id: '14', name: 'PB2/SS', position: { x: 40, y: -45 } },
      { id: '15', name: 'PB3/MOSI', position: { x: 40, y: -35 } },
      { id: '16', name: 'PB4/MISO', position: { x: 40, y: -25 } },
      { id: '17', name: 'PB5/SCK', position: { x: 40, y: -15 } },
      { id: '20', name: 'AVCC', position: { x: 40, y: 5 } },
      { id: '22', name: 'GND', position: { x: 40, y: 15 } },
    ],
    defaultValues: { clock: '16MHz', package: 'DIP-28' },
  },
  {
    id: '74hc595',
    name: 'Shift Reg (74HC595)',
    category: 'Logic',
    symbol: 'ic-16',
    pins: [
      { id: '14', name: 'SER', position: { x: -30, y: -30 } },
      { id: '12', name: 'RCLK', position: { x: -30, y: -10 } },
      { id: '11', name: 'SRCLK', position: { x: -30, y: 10 } },
      { id: '13', name: 'OE', position: { x: -30, y: 30 } },
      { id: '15', name: 'QA', position: { x: 30, y: -40 } },
      { id: '1', name: 'QB', position: { x: 30, y: -30 } },
      { id: '2', name: 'QC', position: { x: 30, y: -20 } },
      { id: '3', name: 'QD', position: { x: 30, y: -10 } },
      { id: '4', name: 'QE', position: { x: 30, y: 0 } },
      { id: '5', name: 'QF', position: { x: 30, y: 10 } },
      { id: '6', name: 'QG', position: { x: 30, y: 20 } },
      { id: '7', name: 'QH', position: { x: 30, y: 30 } },
    ],
    defaultValues: { part: '74HC595' },
  },
  {
    id: 'dht22',
    name: 'DHT22 Sensor',
    category: 'Sensor',
    symbol: 'sensor-dht',
    pins: [
      { id: 'vcc', name: 'VCC', position: { x: -15, y: -20 } },
      { id: 'dat', name: 'DATA', position: { x: -15, y: 0 } },
      { id: 'gnd', name: 'GND', position: { x: -15, y: 20 } },
    ],
    defaultValues: { accuracy: '±2% RH' },
  },
  {
    id: 'mpu6050',
    name: 'MPU-6050 IMU',
    category: 'Sensor',
    symbol: 'module-i2c',
    pins: [
      { id: 'vcc', name: 'VCC', position: { x: -30, y: -30 } },
      { id: 'gnd', name: 'GND', position: { x: -30, y: -10 } },
      { id: 'scl', name: 'SCL', position: { x: 30, y: -30 } },
      { id: 'sda', name: 'SDA', position: { x: 30, y: -10 } },
      { id: 'int', name: 'INT', position: { x: 30, y: 10 } },
    ],
    defaultValues: { range: '±2g / ±250°/s' },
  },
  {
    id: 'vcc',
    name: 'VCC (+5V)',
    category: 'Power',
    symbol: 'power',
    pins: [
      { id: 'vcc', name: 'VCC', position: { x: 0, y: 0 } },
    ],
    defaultValues: { voltage: '5V' },
  },
  {
    id: 'ground',
    name: 'Ground',
    category: 'Power',
    symbol: 'ground',
    pins: [
      { id: 'gnd', name: 'GND', position: { x: 0, y: 0 } },
    ],
    defaultValues: {},
  },
];
